--- 
global: 
  resolve_timeout: 5m
  slack_api_url: "https://hooks.slack.com/services/abc123"
receivers: 
  - 
    name: default
    slack_configs: 
      - 
        channel: "#devops"
        send_resolved: true
  - 
    name: slack_alert
    slack_configs: 
      - 
        channel: "#devops"
        send_resolved: true
route: 
  group_by: 
    - alertname
    - cluster
    - service
  group_interval: 5m
  group_wait: 30s
  receiver: default
  repeat_interval: 15m
  routes: 
    - 
      match: 
        severity: slack
      receiver: slack_alert
    - 
      match: 
        severity: email
      receiver: slack_alert
